### ISSUE TITLE
Changing prop values over time

### ISSUE THREAD

**Issue by goto-bus-stop** [ajkachnic/uppy-vue#1]
In the React components, we support changes to props:

```js
const english = require('@uppy/locales/lib/en_US')
const german = require('@uppy/locales/lib/de_DE')

function MyDash () {
  const [locale, setLocale] = React.useState(english)

  const handleSomeEvent = () => {
    setLocale(german)
  }
  // … imagine some kind of language change event handler or something … 

  return (
    <Dashboard uppy={uppy} locale={locale} />
  )
}
```

The React components implement this by removing and re-adding the plugin, but they are quite old and there is a better way now: the [`setOptions()` functions](https://uppy.io/docs/plugin-options/#setOptions-opts). In React land that would be done in `componentDidUpdate()`, Vue probably has something similar 😇

**Comment by ajkachnic** [comment]
Okay I fixed this in [my Uppy fork on `vue-integration` branch](https://github.com/ajkachnic/uppy/tree/vue-integration)
