### ISSUE TITLE
<DashboardModal open=true/false>

### ISSUE THREAD

**Issue by goto-bus-stop** [ajkachnic/uppy-vue#2]
I'm not totally sure how this would work in Vue, but we should call:
- `dashboardPlugin.closeModal()` when the `open` value changes from true to false
- `dashboardPlugin.openModal()` when the `open` value changes from false to true
in addition to  what the DashboardModal is already doing (i.e. auto opening on mount).

**Comment by ajkachnic** [comment]
This should be setup in [my uppy fork on the `vue-integration` branch](https://github.com/ajkachnic/uppy/tree/vue-integration)
